"""Classify YouTube videos: real performance vs static image+audio.

Heuristics (in order):
  1. Channel ends with "- Topic" -> STATIC (auto-uploaded by record label)
  2. Title contains "Provided to YouTube by" -> STATIC
  3. Description / page contains "Auto-generated by YouTube" -> STATIC
  4. Title contains "(Audio)", "Full Album", "Complete Recording" + uploaded by Topic-like -> likely STATIC
  5. Otherwise -> PROBABLY_HUMAN (needs manual verification or page fetch)

We fetch:
  - oEmbed JSON for {title, author_name}
  - Full watch page (first 200KB) for "Auto-generated by YouTube" and other signals
"""
import sys, json, urllib.request, ssl, re, time
from pathlib import Path
from urllib.error import HTTPError

sys.stdout.reconfigure(encoding='utf-8')

videos = json.loads(Path('C:/Outros/Cravo/.agent/work/videos.json').read_text(encoding='utf-8'))
ids = sorted(videos.keys())
print(f'Total IDs to classify: {len(ids)}', file=sys.stderr)

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'

def fetch(url, n=300000):
  req = urllib.request.Request(url, headers={'User-Agent': UA, 'Accept-Language':'en;q=0.9'})
  with urllib.request.urlopen(req, timeout=20, context=ctx) as r:
    return r.read(n).decode('utf-8', errors='replace')

results = {}
for i, vid in enumerate(ids, 1):
  oembed_url = f'https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={vid}&format=json'
  watch_url = f'https://www.youtube.com/watch?v={vid}'
  entry = {'id': vid, 'usages': videos[vid]}
  try:
    o = json.loads(fetch(oembed_url, 16384))
    entry['title'] = o.get('title','')
    entry['author'] = o.get('author_name','')
    # Quick check: Topic channel
    is_topic = entry['author'].endswith(' - Topic')
    entry['is_topic_channel'] = is_topic
    if is_topic:
      entry['classification'] = 'STATIC'
      entry['reason'] = 'Topic channel (auto-uploaded)'
    else:
      # Fetch watch page snippet to check for Auto-generated tag
      try:
        body = fetch(watch_url, 400000)
        entry['auto_generated'] = 'Auto-generated by YouTube' in body or 'auto-generated by YouTube' in body
        # Check video status (available, removed, private)
        entry['is_available'] = '"playabilityStatus":{"status":"OK"' in body or 'playabilityStatus' not in body or '"status":"OK"' in body
        # Heuristic for static still: short pageOwnerDetails on Topic-derived channels
        # Try to extract description snippet:
        md = re.search(r'"shortDescription":"((?:[^"\\]|\\.){0,500})"', body)
        desc = md.group(1) if md else ''
        entry['desc_snippet'] = desc[:200].encode().decode('unicode_escape', errors='replace')[:200]
        if entry['auto_generated']:
          entry['classification'] = 'STATIC'
          entry['reason'] = 'Description tagged "Auto-generated by YouTube"'
        elif 'Provided to YouTube by' in entry['desc_snippet']:
          entry['classification'] = 'STATIC'
          entry['reason'] = 'Description starts with "Provided to YouTube by"'
        else:
          entry['classification'] = 'PROBABLY_HUMAN'
          entry['reason'] = 'No auto-upload signal'
      except Exception as e:
        entry['classification'] = 'UNKNOWN'
        entry['reason'] = f'watch fetch err: {e}'
  except HTTPError as e:
    if e.code == 401:
      entry['classification'] = 'UNAVAILABLE'
      entry['reason'] = 'oembed 401 (video private/removed/age-restricted)'
    else:
      entry['classification'] = 'UNKNOWN'
      entry['reason'] = f'oembed HTTP {e.code}'
  except Exception as e:
    entry['classification'] = 'UNKNOWN'
    entry['reason'] = f'oembed err: {e}'
  results[vid] = entry
  print(f'[{i:>3}/{len(ids)}] {vid}  {entry.get("classification","?"):<14} {entry.get("author","")[:40]:<40}  {entry.get("title","")[:80]}', flush=True)
  time.sleep(0.3)

Path('C:/Outros/Cravo/.agent/work/video_classification.json').write_text(
  json.dumps(results, ensure_ascii=False, indent=2), encoding='utf-8'
)

# Summary
from collections import Counter
c = Counter(r.get('classification','?') for r in results.values())
print('\n=== SUMMARY ===', file=sys.stderr)
for k, v in c.most_common():
  print(f'  {k}: {v}', file=sys.stderr)
